version: '3'
networks:
  monitoring:
    driver: bridge
services:
  sentinel:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - DB_PATH=data/db.sqlite
    ports:
      - "9100:9100"
    expose:
      - 9100
    volumes:
      - data:/app/data
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          memory: 50M
  prometheus:
    image: prom/prometheus:v2.36.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
      image: grafana/grafana:8.2.6
      container_name: grafana
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning:/etc/grafana/provisioning
        - ./grafana/dashboards/:/etc/grafana/dashboards
        - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      ports:
        - "3000:3000"
      expose:
        - 3000
      networks:
        - monitoring


volumes:
  prometheus_data: { }
  grafana_data: { }
  data: { }

