version: '3'

services:
  solvency:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    volumes:
      - data-volume:/usr/src/app/db.sqlite
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          memory: 50M

volumes:
  data-volume:
