# Minimal version which starts the sentinel service only, without additional monitoring services.
# This may be a better choice for resource constrained environments or for use with custom monitoring setups.
# You can run this version by setting COMPOSE_FILE=docker-compose-minimal.yml in .env.

version: '3'
services:
  sentinel:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - DB_PATH=data/db.sqlite
      # hardcode the port inside the container
      - METRICS_PORT=9100
    ports:
      - ${METRICS_PORT:-9100}:9100
    volumes:
      - data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          memory: 50M

volumes:
  data:
