# Basic docker-compose file for running a sentinel.
# This is ideal for resource constrained environments or for use with custom monitoring setups.

version: '3'
services:
  sentinel:
    image: superfluidfinance/superfluid-sentinel:${SENTINEL_VERSION:-latest}
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      # hardcode the port inside the container
      - METRICS_PORT=9100
    ports:
      - ${METRICS_PORT:-9100}:9100
    volumes:
      - data:/app/data

volumes:
  data:
