# Starts the Sentinel service and connected monitoring services: Prometheus and Grafana.

version: '3'

services:
  # the sentinel image is built from source
  sentinel:
    image: superfluidfinance/superfluid-sentinel
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - DB_PATH=data/db.sqlite
      # hardcode the port inside the container
      - METRICS_PORT=9100
    ports:
      - ${METRICS_PORT:-9100}:9100
    expose:
      - 9100
    volumes:
      - data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          memory: 50M
  prometheus:
    image: prom/prometheus:v2.36.1
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    expose:
      - ${PROMETHEUS_PORT:-9090}
  grafana:
      image: grafana/grafana:8.2.6
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning:/etc/grafana/provisioning
        - ./grafana/dashboards/:/etc/grafana/dashboards
        - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      ports:
        - ${GRAFANA_PORT:-3000}:3000
      expose:
        - ${GRAFANA_PORT:-3000}

volumes:
  prometheus_data:
  grafana_data:
  data:
